#!/bin/bash

# Compile both C files and link them (-lm to link the math library)
gcc ./test/blas_test.c ./src/blas.c -o ./bin/tests/blas_test -lm

# Check if compilation was successful
if [ $? -eq 0 ]; then
    # Run the executable
    ./bin/tests/blas_test
else
    echo "Compilation failed."
fi

