#!/bin/bash

# Compile both C files and link them (-lm to link the math library)
gcc main.c ./src/blas/blas.c -o ./bin/main -lm

# Check if compilation was successful
if [ $? -eq 0 ]; then
    # Run the executable
    ./bin/main
else
    echo "Compilation failed."
fi

